version: "3.9"

services:

  fastapi:
    container_name: boilerplate-api
    build:
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./source:/app/source
      - ./test:/app/test
    depends_on:
      - mongodb

  mongodb:
    container_name: boilerplate-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./config/.env
